//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Install.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Install.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon HanraCircle {
            get {
                object obj = ResourceManager.GetObject("HanraCircle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   [ENGLISH]
        ///Software End User License
        ///Integrated contract
        /// 
        ///
        ///Please read it carefully because it is important.
        ///This Software End User License Agreement (the &quot;License Agreement&quot;) is a contract between the individual or a single company (&quot;User&quot;) and &quot;Company&quot; for software products developed, sold and distributed by Halla Precision Engineering Co., Agreement.
        ///The software that corresponds to this &quot;License Agreement&quot; is the full version (except for the country version) of all the software provided by us an[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string License_E {
            get {
                return ResourceManager.GetString("License_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [한국어]
        ///소프트웨어 최종 사용자 사용권 
        ///통합 계약서
        /// 
        ///
        ///중요한 내용이므로 자세히 읽어 보시기 바랍니다.
        ///본 소프트웨어 최종 사용자 사용권 통합 계약서(이하 “사용권 계약서”)는 (주)한라정밀엔지니어링이 개발, 판매, 배포한 소프트웨어 제품에 대해 개인 또는 단일 업체(이하 “사용자”)와 “회사” 간에 체결하는 사용 계약입니다.  
        ///본 “사용권 계약서”에 해당하는 소프트웨어는 한라 홈페이지(http://www.hanra.co.kr)에서 및 당사에서 제공되는 모든 소프트웨어의 전체 버전(단, 국가별 버전은 제외)입니다.
        ///본 ”회사”의 소프트웨어(이하 “제품”)에는 컴퓨터 소프트웨어뿐만 아니라, “제품”에 부속된 자료, 매체, 파일, 데이터, 인쇄물 및 “온라인” 또는 전자문서(“소프트웨어”) 등이 포함될 수 있습니다.
        ///“사용자”는 본 “제품”의 전부 또는 일부를 컴퓨터 또는 네트워크 상에서 설치, 복사하거나 실행함으로써 본 “사용권 계약서” 내용에 동의하고 사용하는 것으로 간주됩니다.        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string License_K {
            get {
                return ResourceManager.GetString("License_K", resourceCulture);
            }
        }
    }
}
